---
apiVersion: v1
kind: Service
metadata:
  name: setrem-devops-demo
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: setrem-devops-demo
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: setrem-devops-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: setrem-devops-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: setrem-devops-demo
    spec:
      containers:
      - name: devops-demo-app
        image: "gabrielrih/devops-demo-app:latest"
        imagePullPolicy: Always
        # envFrom:
        #   - configMapRef:
        #       name: legado-php-config
        resources:
          limits:
            memory: "128Mi"
            cpu: "1"
