services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.app
    ports:
      - 5000:5000
    networks:
      default:
        aliases:
          - my-ip.dev
  unit_test:
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile.test
    depends_on:
      - app
    command: pytest ./test/unit
  integration_test:
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile.test
    depends_on:
      - app
    command: pytest ./test/integration