FROM cypress/base:20.5.0
WORKDIR /app
COPY ./cypress ./cypress
COPY ./cypress.config.js .
COPY package.json .
COPY package-lock.json . 
RUN npm ci
# verify that Cypress has been installed correctly.
# running this command separately from "cypress run" will also cache its result
# to avoid verifying again when running the tests
RUN npx cypress verify