FROM python:3.11.4-bullseye
WORKDIR /app
COPY ../requirements/ ./requirements/
RUN pip install --no-cache-dir -r ./requirements/common.txt
RUN pip install --no-cache-dir -r ./requirements/dev.txt
COPY ../ .