FROM python:3.11.4-bullseye
WORKDIR /app
COPY ../requirements/ ./requirements/
RUN pip install --no-cache-dir -r ./requirements/common.txt
RUN pip install --no-cache-dir -r ./requirements/dev.txt
COPY ../ .
# CMD ["pytest", "test/integration"]
# CMD ["curl", "127.0.0.0:5000"]