name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  IMAGE_NAME: devops-demo-app

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements/common.txt ]; then pip install -r requirements/common.txt; fi
          if [ -f requirements/dev.txt ]; then pip install -r requirements/dev.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  unit_tests:
    runs-on: ubuntu-latest
    name: Unit tests / Code coverage
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements/common.txt ]; then pip install -r requirements/common.txt; fi
          if [ -f requirements/dev.txt ]; then pip install -r requirements/dev.txt; fi
      - name: Unit test
        run: |
          coverage run -m pytest test/unit
          coverage xml
          echo "Code coverage report:"
          coverage report
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage.xml
          path: ./coverage.xml
  integration_tests:
    runs-on: ubuntu-latest
    name: Integration tests
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements/common.txt ]; then pip install -r requirements/common.txt; fi
          if [ -f requirements/dev.txt ]; then pip install -r requirements/dev.txt; fi
      - name: Integration tests
        run: |
          docker compose -f ./docker/compose-test.yml up --build --abort-on-container-exit
  security_scan:
    runs-on: ubuntu-latest
    name: Security scan
    needs: [checks, unit_tests, integration_tests]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements/common.txt ]; then pip install -r requirements/common.txt; fi
          if [ -f requirements/dev.txt ]; then pip install -r requirements/dev.txt; fi
      - name: Vulnerability scan on packages
        run: |
          safety check -r requirements/common.txt
      - name: Vulnerability scan on dev packages
        run: |
          safety check -r requirements/dev.txt
      - name: Download artifact coverage.xml
        uses: actions/download-artifact@v3
        with:
          name: coverage.xml
      # FIX IT
      # The coverage in 0%
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build_image:
    runs-on: ubuntu-latest
    name: Build and push image
    needs: [security_scan]
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        run: |
          current_image="${{ env.IMAGE_NAME }}:$GITHUB_SHA"
          echo "Building image $current_image"
          docker build -f ./docker/Dockerfile.app -t "${{ secrets.DOCKERHUB_USERNAME }}/$current_image" .
          docker image ls
          
          echo "Pushing image"
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/$current_image"

          if [ "$GITHUB_REF_NAME" == "master" ] || [ "$GITHUB_REF_NAME" == "main" ]; then
            latest_image="${{ env.IMAGE_NAME }}:latest"
            echo "Creating the latest image: $latest_image"
            docker tag "${{ secrets.DOCKERHUB_USERNAME }}/$current_image" "${{ secrets.DOCKERHUB_USERNAME }}/$latest_image"
            docker image ls
            
            echo "Pushing latest image"
            docker push "${{ secrets.DOCKERHUB_USERNAME }}/$latest_image"
  